[project]
name = "loc-responsible-datasets-01-bills"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
    "typer>=0.15.1",
]
